# Generated by Django 2.2.3 on 2019-09-10 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavedEmbed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1000)),
                ('maxwidth', models.SmallIntegerField(blank=True, null=True)),
                ('type', models.CharField(choices=[('video', 'video'), ('photo', 'photo'), ('link', 'link'), ('rich', 'rich')], max_length=10)),
                ('html', models.TextField(blank=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('url', 'maxwidth')},
            },
        ),
    ]
